-- 코드를 입력하세요
-- the codes below are not working
# SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# WHERE BETWEEN HOUR >= 9 AND HOUR <= 19;

-- the codes below are working
SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR >= 9 AND HOUR <= 19 # having에는 between이 들어가지 않음!
ORDER BY HOUR