-- [프로그래머스] 동명 동물 수 찾기

-- solution 1
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT >=2
ORDER BY NAME

-- solution 2
SELECT NAME, COUNT
FROM (
    SELECT NAME, COUNT(NAME) AS COUNT
    FROM ANIMAL_INS
    GROUP BY NAME
) SQ1
WHERE COUNT >=2
ORDER BY NAME
